<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Version>1.0.1.0</Version>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <Configurations>Debug;Release;debug libs</Configurations>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Title>Custom json configuration provider</Title>
	  <PackageOutputPath>$(SolutionDir)\packages</PackageOutputPath>
	  <PackageId>$(AssemblyName)</PackageId>
	  <PackageVersion>$(Version)</PackageVersion>
	  <Authors>innasolp</Authors>
	  <RepositoryUrl>https://github.com/innasolp/Configuration</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomConfigurationProvider\CustomConfigurationProvider.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
	</ItemGroup>
	
</Project>
